# Generated by Django 2.0.3 on 2018-04-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
    ]
