# Generated by Django 2.0.3 on 2018-03-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operating_system',
            name='version_no',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
