# Generated by Django 2.0.3 on 2018-03-14 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_operating_system_os_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='operating_system',
            name='version_no',
            field=models.ForeignKey(default=7.7, on_delete=django.db.models.deletion.CASCADE, to='inventory.Version'),
            preserve_default=False,
        ),
    ]
